version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      cayambeNetwork:
        ipv4_address: 172.20.0.3
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    networks:
      cayambeNetwork:
        ipv4_address: 172.20.0.4
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
networks:
  cayambeNetwork:
    name: cayambeNetwork
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
