version: '3.7'

services:
  connect:
    image: debezium/connect-jdbc:1.3
    build:
      context: debezium-jdbc
    container_name: debezium_connect_jdbc
    ports:
      - 8083:8083
    networks:
      cayambeNetwork:
        ipv4_address: 172.20.0.7
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
networks:
  cayambeNetwork:
    name: cayambeNetwork
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
