version: '3.7'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
    networks:
      cayambeNetwork:
        ipv4_address: 172.20.0.2
    volumes:
      - ${HOME}/mysql/data:/var/lib/mysql
      - ../../:/home/sql
networks:
  cayambeNetwork:
    name: cayambeNetwork
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
